name: Validate

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Hassfest Validation
        uses: home-assistant/actions/hassfest@master
